import base64
import json
import tempfile
import threading
import unittest
from datetime import datetime, timedelta
from http.server import ThreadingHTTPServer
from pathlib import Path
from unittest.mock import patch

import app

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    sync_playwright = None


@unittest.skipIf(sync_playwright is None, "playwright is not installed")
class DataProtectionBrowserTest(unittest.TestCase):
    def test_database_integrity_button(self):
        errors = []
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            patchers = [
                patch.object(app, "CONFIG_DIR", root),
                patch.object(app, "DATA_FILE", root / "test.sqlite3"),
                patch.object(app, "CONFIG_FILE", root / "settings.json"),
                patch.object(app, "BACKUP_DIR", root / "backups"),
                patch.object(app, "PORT", 0),
            ]
            for patcher in patchers:
                patcher.start()
            with app.db_connect() as conn:
                conn.execute("SELECT 1")
            app.save_entry({"area": "todos", "title": "Snooze this task", "due_date": datetime.now().strftime("%Y-%m-%d")})
            app.save_entry({"area": "todos", "title": "Complete from task list"})
            app.save_finance({"direction": "expense", "title": "Upcoming electric bill", "amount": "75", "frequency": "monthly", "due_day": (datetime.now() + timedelta(days=2)).day})
            app.save_goal({"title": "Organize the garden", "description": "Choose one manageable first step.", "priority": 1})
            app.store_uploaded_file({"name": "Tagged library.txt", "content": base64.b64encode(b"sample document").decode("ascii"), "importance": "critical", "category": "General"})
            app.store_uploaded_file({"name": "pixel.png", "content": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lXcAAAAASUVORK5CYII=", "importance": "critical", "category": "General"})
            app.backup.create_daily_backup(app.DATA_FILE, app.BACKUP_DIR, settings_path=app.CONFIG_FILE)
            server = ThreadingHTTPServer((app.HOST, 0), app.Handler)
            app.PORT = server.server_address[1]
            thread = threading.Thread(target=server.serve_forever, daemon=True)
            thread.start()
            try:
                with sync_playwright() as p:
                    browser = p.chromium.launch()
                    try:
                        page = browser.new_page()
                        page.context.grant_permissions(["notifications"], origin=f"http://{app.HOST}:{app.PORT}")
                        dialogs = []
                        page.on("pageerror", lambda error: errors.append(str(error) + " " + error.stack))
                        page.on("dialog", lambda dialog: (dialogs.append(dialog.message), dialog.accept()))
                        def mock_ollama_status(route):
                            route.fulfill(status=200, content_type="application/json", body=json.dumps({
                                "available": True, "model_available": True, "model": "test-model",
                                "models": ["test-model"], "message": "Configured model is ready.",
                            }))
                        page.route("**/api/ollama/status", mock_ollama_status)
                        page.goto(f"http://{app.HOST}:{app.PORT}/")
                        try:
                            page.wait_for_selector("#nav button", timeout=5000)
                        except Exception as error:
                            source = Path(app.WEB_DIR / "index.html").read_text(encoding="utf-8")
                            script = source.split("<script>", 1)[1].split("</script>", 1)[0]
                            syntax = page.evaluate("source => { try { new Function(source); return 'syntax ok' } catch (error) { return error.stack } }", script)
                            raise AssertionError(f"App navigation did not load; page errors: {errors}; parser: {syntax}") from error
                        page.get_by_role("heading", name="Welcome to Phillap").wait_for()
                        page.get_by_role("button", name="Next", exact=True).click()
                        page.get_by_role("heading", name="Your data and choices").wait_for()
                        page.get_by_role("button", name="Next", exact=True).click()
                        page.get_by_role("heading", name="Make it yours").wait_for()
                        page.get_by_role("button", name="Start using Phillap").click()
                        page.get_by_role("dialog", name="Make it yours").wait_for(state="hidden")
                        page.locator(".reading-settings > summary").click()
                        page.locator("#theme-select").select_option("light")
                        self.assertEqual(page.locator("body").get_attribute("data-theme"), "light")
                        page.locator("#theme-select").select_option("forest")
                        page.locator(".reading-settings > summary").click()
                        update_url = f"https://github.com/{app.DEFAULT_REPO}/releases/tag/v0.0.5"
                        page.route("**/api/update", lambda route: route.fulfill(status=200, content_type="application/json", body=json.dumps({"current_version": app.APP_VERSION, "latest_version": "0.0.5", "update_available": True, "release_url": update_url})))
                        page.locator(".reading-settings > summary").click()
                        page.get_by_role("button", name="Check for updates").click()
                        update_link = page.get_by_role("link", name="View release")
                        update_link.wait_for()
                        self.assertEqual(update_link.get_attribute("href"), update_url)
                        page.locator(".reading-settings > summary").click()
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Today", exact=True).click()
                        page.get_by_text("Upcoming electric bill", exact=True).wait_for()
                        page.locator("#today-widget-settings summary").click()
                        page.get_by_role("button", name="Move Done today up").click()
                        widget_order = page.locator("[data-today-widget]").evaluate_all("items => items.map(item => item.dataset.todayWidget)")
                        self.assertLess(widget_order.index("done"), widget_order.index("snoozed"))
                        page.reload()
                        page.locator("[data-today-widget]").first.wait_for()
                        widget_order = page.locator("[data-today-widget]").evaluate_all("items => items.map(item => item.dataset.todayWidget)")
                        self.assertLess(widget_order.index("done"), widget_order.index("snoozed"))
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Today", exact=True).click()
                        page.locator("#search-q").wait_for()
                        summary_requests = []
                        def mock_daily_summary(route):
                            summary_requests.append(route.request.post_data_json)
                            route.fulfill(status=200, content_type="application/json", body=json.dumps({
                                "summary": "A small, steady day is still progress.", "sources": [],
                            }))
                        page.route("**/api/assistant/daily-summary", mock_daily_summary)
                        page.get_by_role("button", name="Generate today's summary").click()
                        page.get_by_text("A small, steady day is still progress.").wait_for()
                        self.assertEqual(summary_requests, [{}])
                        page.unroute("**/api/assistant/daily-summary", mock_daily_summary)
                        page.locator("body").press("/")
                        self.assertEqual(page.evaluate("document.activeElement.id"), "search-q")
                        page.locator("body").click(position={"x": 5, "y": 5})
                        page.locator("body").press("n")
                        page.get_by_role("dialog", name="Quick add task or reminder").wait_for()
                        page.locator("body").press("Escape")
                        page.get_by_role("dialog", name="Quick add task or reminder").wait_for(state="detached")
                        page.locator("#focus-task .focus-title").get_by_text("Snooze this task", exact=True).wait_for()
                        page.get_by_role("button", name="Open weekly review").click()
                        page.get_by_role("heading", name="Weekly review").wait_for()
                        page.get_by_role("heading", name="Completed this week").wait_for()
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Today", exact=True).click()
                        page.get_by_role("button", name="Show another task").click()
                        page.locator("#focus-task .focus-title").get_by_text("Complete from task list", exact=True).wait_for()
                        page.get_by_role("button", name="Show another task").click()
                        page.locator("#focus-task .focus-title").get_by_text("Snooze this task", exact=True).wait_for()
                        page.get_by_role("button", name="Plan my day").click()
                        page.locator("#page-title").get_by_text("To-dos", exact=True).wait_for()
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Today", exact=True).click()
                        page.get_by_text("Snooze this task", exact=True).first.wait_for()
                        page.get_by_role("button", name="Snooze 1 hour").first.click()
                        page.get_by_text("Snoozed (1)").wait_for()
                        page.get_by_role("button", name="Unsnooze").click()
                        page.get_by_text("Snoozed (0)").wait_for()
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Tasks", exact=True).click()
                        page.get_by_role("checkbox", name="Mark Complete from task list complete").check()
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Today", exact=True).click()
                        page.get_by_text("Done today (1)").wait_for()
                        page.get_by_text("Complete from task list", exact=True).wait_for()
                        page.get_by_role("button", name="Reopen").click()
                        page.get_by_text("Done today (0)").wait_for()
                        page.locator("#search-q").fill("Snooze")
                        page.locator("#search-form").get_by_role("button", name="Search").click()
                        page.locator("#search-results mark").filter(has_text="Snooze").first.wait_for()
                        page.get_by_label("Filter by area").select_option("todos")
                        page.get_by_label("Filter by type").select_option("entry")
                        page.get_by_label("Filter by date").fill(datetime.now().strftime("%Y-%m-%d"))
                        page.locator("#search-results").get_by_role("button", name="Open").wait_for()
                        page.get_by_label("Filter by date").fill("")
                        page.get_by_role("button", name="Save this search").click()
                        page.get_by_role("button", name="Run saved search Snooze").wait_for()
                        page.get_by_role("button", name="Run recent search Snooze").wait_for()
                        page.get_by_role("button", name="Run saved search Snooze").click()
                        page.get_by_text("1 results.").wait_for()
                        page.get_by_role("button", name="Remove saved search Snooze").click()
                        page.get_by_text("Saved search removed.").wait_for()
                        page.get_by_role("button", name="Previous month").click()
                        page.get_by_role("button", name="Next month").click()
                        page.get_by_role("grid", name="To-do calendar").wait_for()
                        page.locator("#search-results").get_by_role("button", name="Open").first.click()
                        page.locator('[data-entry-id="1"]').wait_for()
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Files", exact=True).click()
                        page.get_by_role("button", name="Preview").wait_for()
                        page.get_by_role("button", name="Preview").click()
                        preview_dialog = page.get_by_role("dialog", name="File preview")
                        preview_dialog.wait_for()
                        page.wait_for_function("document.querySelector('#file-preview-image').naturalWidth === 1")
                        page.get_by_role("button", name="Close preview").click()
                        preview_dialog.wait_for(state="detached")
                        tagged_file_row = page.locator("#file-list .entry").filter(has_text="Tagged library.txt")
                        tagged_file_row.get_by_role("textbox", name="Tags for Tagged library.txt").fill("tax, yearly")
                        tagged_file_row.get_by_role("button", name="Save tags").click()
                        page.get_by_text("Tags saved for Tagged library.txt.").wait_for()
                        page.locator("#library-search").fill("yearly")
                        page.get_by_text("Tagged library.txt", exact=True).wait_for()
                        page.get_by_role("navigation", name="Life areas").get_by_role("button", name="Money", exact=True).click()
                        page.locator("#finance-direction").select_option("expense")
                        page.locator("#finance-title").fill("Rent")
                        page.locator("#finance-amount").fill("150")
                        page.locator("#finance-category").fill("Housing")
                        page.locator("#finance-form").get_by_role("button", name="Add to monthly picture").click()
                        page.get_by_text("Saved locally. Your monthly picture is updated.").wait_for()
                        page.locator("#budget-category").fill("Housing")
                        page.locator("#budget-amount").fill("100")
                        page.locator("#finance-budget-form").get_by_role("button", name="Save budget").click()
                        page.get_by_text("Housing · $100.00/month").wait_for()
                        budget_display = page.locator("#finance-budgets .entry-meta").inner_text()
                        self.assertIn("$150.00", budget_display)
                        self.assertIn("$50.00 over", budget_display)
                        self.assertEqual(page.locator("#finance-budgets progress").get_attribute("value"), "100.0")
                        page.locator("#savings-title").fill("Emergency fund")
                        page.locator("#savings-target").fill("1000")
                        page.locator("#savings-date").fill("2027-06-01")
                        page.locator("#savings-goal-form").get_by_role("button", name="Add savings goal").click()
                        savings_card = page.locator("#savings-goals .entry").filter(has_text="Emergency fund")
                        savings_card.get_by_label("Contribution (USD)").fill("125")
                        savings_card.get_by_role("button", name="Log contribution").click()
                        page.get_by_text("Saved $125.00 of $1,000.00 · $875.00 remaining").wait_for()
                        page.locator("#net-worth-title").fill("Savings account")
                        page.locator("#net-worth-type").select_option("asset")
                        page.locator("#net-worth-amount").fill("1500")
                        page.locator("#net-worth-category").fill("Cash")
                        page.locator("#net-worth-form").get_by_role("button", name="Add balance").click()
                        page.locator("#net-worth-items .entry").filter(has_text="Savings account").wait_for()
                        page.wait_for_function("document.querySelector('#net-worth-assets').textContent === '$1,500.00'")
                        self.assertEqual(page.locator("#net-worth-assets").inner_text(), "$1,500.00")
                        page.locator("#debt-title").fill("Card balance")
                        page.locator("#debt-balance").fill("1200")
                        page.locator("#debt-apr").fill("0")
                        page.locator("#debt-payment").fill("100")
                        page.locator("#debt-form").get_by_role("button", name="Add debt estimate").click()
                        page.get_by_text("Estimated payoff: 12 months · estimated interest $0.00 · total payments $1,200.00").wait_for()
                        page.locator("#transaction-title").fill("Market")
                        page.locator("#transaction-amount").fill("25")
                        page.locator("#transaction-date").fill("2025-03-02")
                        page.locator("#transaction-category").fill("Food")
                        page.locator("#finance-transaction-form").get_by_role("button", name="Add transaction").click()
                        page.get_by_text("Transaction saved locally.").wait_for()
                        page.locator("#report-year").fill("2025")
                        page.get_by_role("button", name="Load report").click()
                        page.get_by_text("Loaded 1 transactions for 2025.").wait_for()
                        self.assertEqual(page.locator("#report-expenses").inner_text(), "−$25.00")
                        self.assertEqual(page.locator("#finance-report-export").get_attribute("href"), "/api/finance/report.csv?year=2025")
                        assistant_requests = []
                        def mock_assistant_chat(route):
                            assistant_requests.append(route.request.post_data_json)
                            route.fulfill(status=200, content_type="application/json", body=json.dumps({
                                "answer": "A locally grounded next step.", "sources": [], "conversation_id": 999,
                            }))
                        page.route("**/api/chat", mock_assistant_chat)
                        page.locator("#nav").get_by_role("button", name="Assistant", exact=True).click()
                        page.locator("#include-today-goals").wait_for()
                        page.get_by_text("Configured model is ready.", exact=True).wait_for()
                        self.assertEqual(page.locator("#model-picker option").all_inner_texts(), ["test-model"])
                        self.assertEqual(page.locator("#model-picker").input_value(), "test-model")
                        self.assertFalse(page.locator("#include-today-goals").is_checked())
                        page.locator("#include-today-goals").check()
                        page.locator("#question").fill("What should I focus on?")
                        page.get_by_role("button", name="Ask", exact=True).click()
                        page.get_by_text("A locally grounded next step.").wait_for()
                        self.assertTrue(assistant_requests[0]["include_today_goals"])
                        page.unroute("**/api/chat", mock_assistant_chat)
                        goal_requests = []
                        def mock_goal_suggestions(route):
                            goal_requests.append(route.request.post_data_json)
                            route.fulfill(status=200, content_type="application/json", body=json.dumps({
                                "suggestions": "Pick one seed or tool to research.",
                            }))
                        page.route("**/api/goals/next-steps", mock_goal_suggestions)
                        page.locator("#nav").get_by_role("button", name="Big goals", exact=True).click()
                        page.get_by_role("button", name="Suggest next steps").click()
                        page.get_by_text("Pick one seed or tool to research.").wait_for()
                        self.assertEqual(len(goal_requests), 1)
                        page.unroute("**/api/goals/next-steps", mock_goal_suggestions)
                        page.get_by_role("button", name="Data protection", exact=True).click()
                        page.wait_for_selector("#integrity-check")
                        weekly = page.locator("#weekly-backups")
                        self.assertTrue(weekly.is_checked())
                        weekly.uncheck()
                        page.get_by_text("Weekly backups disabled.").wait_for()
                        page.get_by_role("button", name="Check database integrity").click()
                        page.get_by_text("Database integrity check passed.").wait_for()
                        page.get_by_role("button", name="Verify", exact=True).click()
                        page.get_by_text("Backup verified:").wait_for()
                        with page.expect_navigation(wait_until="domcontentloaded"):
                            page.get_by_role("button", name="Restore", exact=True).click()
                        self.assertTrue(dialogs)
                        self.assertIn("Contents:", dialogs[0])
                        self.assertIn("Database records:", dialogs[0])
                        page.get_by_role("button", name="Data protection", exact=True).click()
                        page.wait_for_selector("#backup-folder")
                        custom_dir = str(root / "custom backups")
                        page.locator("#backup-folder").fill(custom_dir)
                        page.get_by_role("button", name="Save folder").click()
                        page.get_by_text("Backup folder saved.").wait_for()
                        self.assertTrue(Path(page.locator("#backup-folder").input_value()).samefile(custom_dir))
                        with patch.object(app.os, "startfile", create=True) as open_folder:
                            page.get_by_role("button", name="Open backup folder").click()
                            page.get_by_text("Opened the backup folder.").wait_for()
                            self.assertEqual(open_folder.call_args.args[0], str(Path(custom_dir).resolve()))
                        csv_path = root / "browser-todos.csv"
                        csv_path.write_text("title,content,due_date,due_time,priority,tags\nImported from browser,temporary,2031-01-02,15:45,1,errands\n", encoding="utf-8")
                        page.locator("#csv-import-file").set_input_files(str(csv_path))
                        page.get_by_role("button", name="Import CSV").click()
                        page.get_by_text("Imported 1 to-do records.").wait_for()
                        json_path = root / "browser-export.json"
                        json_path.write_text(json.dumps(app.backup.export_json(app.DATA_FILE)), encoding="utf-8")
                        with app.db_connect() as conn:
                            conn.execute("INSERT INTO entries(area,title) VALUES('todos','Removed by JSON import')")
                        page.locator("#json-import-file").set_input_files(str(json_path))
                        with page.expect_navigation(wait_until="domcontentloaded"):
                            page.get_by_role("button", name="Import JSON").click()
                        self.assertIn("Settings and uploaded files will not be replaced", dialogs[-1])
                        page.wait_for_load_state("networkidle")
                        page.get_by_role("button", name="More", exact=True).click()
                        page.get_by_role("button", name="To-dos", exact=True).click()
                        page.get_by_role("button", name="Delete Imported from browser").wait_for()
                        page.get_by_text("Due 2031-01-02 at 15:45").wait_for()
                        page.get_by_text("High priority").wait_for()
                        page.get_by_text("Tags: errands").wait_for()
                        page.get_by_role("button", name="Delete Imported from browser").click()
                        page.get_by_text("Moved to Recycle bin.").wait_for()
                        page.get_by_role("button", name="More", exact=True).click()
                        page.get_by_role("button", name="Recycle bin", exact=True).click()
                        page.get_by_role("button", name="Restore", exact=True).click()
                        page.get_by_text("Entry restored to To-dos.").wait_for()
                        page.get_by_role("button", name="More", exact=True).click()
                        page.get_by_role("button", name="To-dos", exact=True).click()
                        page.get_by_role("button", name="Delete Imported from browser").wait_for()
                        imported_task = page.get_by_role("article").filter(has_text="Imported from browser")
                        imported_task.get_by_text("Subtasks (0)").click()
                        page.get_by_role("textbox", name="Add subtask to Imported from browser").fill("Pack essentials")
                        page.get_by_role("textbox", name="Add subtask to Imported from browser").press("Enter")
                        page.get_by_role("article").filter(has_text="Imported from browser").get_by_text("Subtasks (1)").click()
                        page.get_by_text("Pack essentials", exact=True).wait_for()
                        page.get_by_role("button", name="More", exact=True).click()
                        page.get_by_role("button", name="To-dos", exact=True).click()
                        page.get_by_text("Imported from browser", exact=True).wait_for()
                        page.locator("#entry-title").fill("Weekly recurring check")
                        page.locator("#entry-due").fill("2031-06-02")
                        page.locator("#entry-recurrence").select_option("weekly")
                        page.locator("#entry-form").get_by_role("button", name="Save").click()
                        recurring_card = page.get_by_role("article").filter(has_text="Weekly recurring check")
                        recurring_card.get_by_text("Repeats weekly").wait_for()
                        recurring_card.get_by_role("checkbox", name="Mark Weekly recurring check complete").check()
                        page.get_by_text("Due 2031-06-09", exact=True).wait_for()
                        source_card = page.locator("#area-list [data-entry-id]").filter(has_text="Due 2031-06-02")
                        target_card = page.locator("#area-list [data-entry-id]").filter(has_text="Imported from browser")
                        source_card.get_by_role("button", name="Drag to reorder Weekly recurring check").drag_to(target_card)
                        page.get_by_role("button", name="Refresh").click()
                        ordered_cards = page.locator("#area-list [data-entry-id]")
                        self.assertIn("Weekly recurring check", ordered_cards.first.inner_text())
                        self.assertIn("Imported from browser", ordered_cards.nth(1).inner_text())
                        page.locator("#entry-title").fill("Swipe complete test")
                        page.locator("#entry-form").get_by_role("button", name="Save").click()
                        swipe_card = page.locator("#area-list [data-entry-id]").filter(has_text="Swipe complete test")
                        swipe_id = swipe_card.get_attribute("data-entry-id")
                        page.evaluate("""card => { const r=card.getBoundingClientRect(),x=r.left+20,y=r.top+r.height/2; card.dispatchEvent(new PointerEvent('pointerdown',{pointerId:1,pointerType:'touch',button:0,clientX:x,clientY:y,bubbles:true})); card.dispatchEvent(new PointerEvent('pointermove',{pointerId:1,pointerType:'touch',button:0,clientX:x+120,clientY:y+4,bubbles:true})); card.dispatchEvent(new PointerEvent('pointerup',{pointerId:1,pointerType:'touch',button:0,clientX:x+120,clientY:y+4,bubbles:true})); }""", swipe_card.element_handle())
                        page.wait_for_function("id => document.querySelector(`[data-entry-id=\"${id}\"] input[type=checkbox]`)?.checked", arg=swipe_id)
                        self.assertTrue(page.locator(f'[data-entry-id="{swipe_id}"] input[type="checkbox"]').is_checked())
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Today", exact=True).click()
                        page.get_by_role("button", name="Enable browser reminders").click()
                        page.get_by_text("Notifications are blocked in browser settings.").wait_for()
                        page.get_by_role("button", name="Enable browser reminders").wait_for()
                        self.assertTrue(page.evaluate("isQuietTime('23:30')"))
                        self.assertTrue(page.evaluate("isQuietTime('06:59')"))
                        self.assertFalse(page.evaluate("isQuietTime('12:00')"))
                        page.locator("#quiet-start").fill("13:00")
                        page.locator("#quiet-end").fill("14:00")
                        self.assertTrue(page.evaluate("isQuietTime('13:30')"))
                        self.assertFalse(page.evaluate("isQuietTime('23:30')"))
                        self.assertEqual(page.evaluate("quietHours().start"), "13:00")
                        page.get_by_text("Turn a pasted note into tasks", exact=True).click()
                        page.locator("#note-to-tasks-input").fill("- Call the dentist\n2. Compare project options")
                        page.get_by_role("button", name="Preview task titles").click()
                        preview_rows = page.locator("#note-to-tasks-preview-list .today-row")
                        self.assertEqual(preview_rows.count(), 2)
                        preview_rows.nth(1).get_by_role("checkbox").uncheck()
                        page.get_by_role("button", name="Save selected tasks").click()
                        page.get_by_text("Saved 1 tasks on this PC.").wait_for()
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="Tasks", exact=True).click()
                        page.get_by_text("Call the dentist", exact=True).wait_for()
                        self.assertEqual(page.get_by_text("Compare project options", exact=True).count(), 0)
                        page.get_by_text("Reading & appearance", exact=True).click()
                        page.get_by_text("Customize bottom navigation", exact=True).click()
                        files_nav_option = page.get_by_label("Show Files in bottom navigation")
                        files_nav_option.uncheck()
                        self.assertEqual(page.get_by_role("navigation", name="Main").get_by_role("button", name="Files", exact=True).count(), 0)
                        page.get_by_role("navigation", name="Main").get_by_role("button", name="More").click()
                        page.locator("#more-menu").get_by_role("button", name="Files", exact=True).wait_for()
                        files_nav_option.check()
                        page.locator("#more-menu").wait_for(state="detached")
                        page.locator("#nav").get_by_role("button", name="Food & Pantry", exact=True).click()
                        page.get_by_role("heading", name="Two-week meal plan").wait_for()
                        page.locator("#food-meal-type").select_option("dinner")
                        page.locator("#food-meal-title").fill("Leftover <script> dinner")
                        page.locator("#food-meal-ingredients").fill("Roast and vegetables; check ingredient labels")
                        page.locator("#food-meal-instructions").fill("Reheat leftovers.")
                        page.locator("#food-meal-leftovers").check()
                        page.get_by_role("button", name="Add to meal plan").click()
                        page.get_by_text("Meal added to your local plan.").wait_for()
                        page.get_by_text("Dinner: Leftover <script> dinner", exact=True).wait_for()
                        self.assertEqual(page.locator("#food-plan-days script").count(), 0)
                        page.get_by_role("button", name="Remove dinner Leftover <script> dinner").click()
                        page.get_by_text("No meals planned.").first.wait_for()
                        page.locator("#food-grocery-item").fill("Eggs")
                        page.locator("#food-grocery-quantity").fill("1 dozen")
                        page.get_by_role("button", name="Add grocery item").click()
                        page.get_by_text("Saved locally on this PC.").first.wait_for()
                        page.get_by_text("Eggs", exact=True).wait_for()
                        page.get_by_role("checkbox", name="Mark Eggs as collected").check()
                        page.get_by_role("checkbox", name="Mark Eggs as collected").wait_for()
                        self.assertTrue(page.get_by_role("checkbox", name="Mark Eggs as collected").is_checked())
                        page.locator("#food-recipe-title").fill("Roast <script> dinner")
                        page.locator("#food-recipe-ingredients").fill("Roast, vegetables")
                        page.locator("#food-recipe-instructions").fill("Check ingredient labels.")
                        page.get_by_role("button", name="Save recipe").click()
                        page.get_by_text("Roast <script> dinner", exact=True).wait_for()
                        page.locator("#food-pantry-item").fill("Rice")
                        page.locator("#food-pantry-quantity").fill("One bag")
                        page.locator("#food-pantry-expiry").fill("2032-12-31")
                        page.get_by_role("button", name="Add pantry item").click()
                        page.get_by_text("Rice", exact=True).wait_for()
                        page.get_by_text("Date: 2032-12-31", exact=True).wait_for()
                        page.locator("#nav").get_by_role("button", name="Habits", exact=True).click()
                        page.locator("#habit-name").fill("Read a little")
                        page.get_by_role("button", name="Add habit").click()
                        habit_check = page.get_by_role("checkbox", name="Mark Read a little done today")
                        habit_check.wait_for()
                        habit_check.check()
                        page.get_by_text("1 of 7 days", exact=True).wait_for()
                        page.locator("#nav").get_by_role("button", name="Health log", exact=True).click()
                        self.assertIn("not medical advice", page.locator("#page").inner_text())
                        page.locator("#life-title").fill("Daily note")
                        page.locator("#life-details").fill("Private local note")
                        page.get_by_role("button", name="Save locally").click()
                        page.get_by_text("Daily note", exact=True).wait_for()
                        page.get_by_text("Private local note", exact=True).wait_for()
                        with app.db_connect() as conn:
                            imported_titles = [row[0] for row in conn.execute("SELECT title FROM entries")]
                        self.assertIn("Imported from browser", imported_titles)
                        self.assertNotIn("Removed by JSON import", imported_titles)
                        page.evaluate("show('data')")
                        page.locator("#backup-passphrase").fill("browser passphrase 123")
                        page.get_by_role("button", name="Create encrypted backup").click()
                        page.get_by_text("Encrypted backup saved as", exact=False).wait_for()
                        page.locator('button[data-verify][data-encrypted="true"]').wait_for()
                        page.locator("#setup-lock-pin").fill("246810")
                        page.get_by_role("button", name="Enable PIN lock").click()
                        page.get_by_text("PIN lock enabled.", exact=False).wait_for()
                        page.get_by_role("button", name="Lock Phillap").click()
                        page.get_by_role("heading", name="Phillap is locked").wait_for()
                        page.reload()
                        page.get_by_role("heading", name="Phillap is locked").wait_for()
                        page.locator("#unlock-pin").fill("135790")
                        page.get_by_role("button", name="Unlock").click()
                        page.get_by_text("That PIN is incorrect.").wait_for()
                        page.locator("#unlock-pin").fill("246810")
                        page.get_by_role("button", name="Unlock").click()
                        page.locator("#nav button").first.wait_for()
                        page.get_by_role("button", name="Lock Phillap").wait_for()
                    finally:
                        browser.close()
            finally:
                server.shutdown()
                server.server_close()
                thread.join(timeout=5)
                for patcher in reversed(patchers):
                    patcher.stop()
        self.assertEqual(errors, [])


if __name__ == "__main__":
    unittest.main()
